### PR TITLE
Added API call for variables by name

### PR DESCRIPTION
**Pull request by jghaanstra**
The current API "all" call returns a unsorted list. I needed better access to to variables so I created an extra API call named "allids" which generates a list by name. Perhaps this is something you can incorporate in a future version (so I dont need to keep track of my own modified version :-) ).

### CODE REVIEW

**Comment by PatrickSannes** [comment]
I'll take a look at this the coming week!

**Comment by PatrickSannes** [comment]
Wouldnt it be nice to make a new call for this change instead of using the existing one?

**Comment by jghaanstra** [comment]
That's up to you. But while tinkering with my setup I have come up with a different solution that does not require this functionality anymore. You can decline this PR if you want.

**Comment by PatrickSannes** [comment]
I think it would be a nice feature. So I'll implement it as /variables.
Makes the most sense to me.

**Pull request closed without merging**
